apiVersion: v1
kind: ConfigMap
metadata:
  name: insightair-config
  namespace: airflow
data:
  environment.yaml: |
    # InsightAir Framework - Environment Configuration
    # Kubernetes deployment configuration
    ---
    # Global Environment Settings
    environment: production
    version: "1.0.0"

    # Cloud Provider Settings
    cloud:
      provider: aws
      region: us-east-1
      
    # Storage Configuration
    storage:
      raw_bucket: "insightair-prod-raw"
      stage_bucket: "insightair-prod-stage"
      archive_bucket: "insightair-prod-archive"
      config_bucket: "insightair-prod-config"
      file_retention_days: 30
      max_file_size_mb: 1024

    # Processing Engine Configuration
    engines:
      default_engine: glue
      timeout_minutes: 60
      retry_count: 3
      
      glue:
        max_concurrent_runs: 10
        worker_type: "G.1X"
        number_of_workers: 2

    # Data Groups
    data_groups:
      production:
        raw_bucket: "insightair-prod-raw"
        stage_bucket: "insightair-prod-stage"
        archive_bucket: "insightair-prod-archive"
        database_host: "prod-db.example.com"
        database_port: 5432

    # Connections
    connections:
      aws_default: "aws_default"
      aws_s3: "aws_s3_conn"
      aws_glue: "aws_glue_conn"

    # Monitoring
    monitoring:
      enable_metrics: true
      log_level: INFO
      alert_emails:
        - ops@company.com

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-webserver
  namespace: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-webserver
  template:
    metadata:
      labels:
        app: airflow-webserver
    spec:
      containers:
      - name: airflow-webserver
        image: apache/airflow:2.7.0
        ports:
        - containerPort: 8080
        env:
        - name: AIRFLOW__CORE__EXECUTOR
          value: "KubernetesExecutor"
        - name: AIRFLOW_ENV
          value: "production"
        - name: CLOUD_PROVIDER
          value: "aws"
        volumeMounts:
        - name: config-volume
          mountPath: /usr/local/airflow/config_files
          readOnly: true
        - name: dags-volume
          mountPath: /opt/airflow/dags
          readOnly: true
      volumes:
      - name: config-volume
        configMap:
          name: insightair-config
      - name: dags-volume
        emptyDir: {} # Replace with persistent volume or git-sync